language: go

env:
  - COUCH_HOST_URL=http://localhost:5984 COUCH_USER=anna COUCH_PASS=secret

before_install:
  - chown -R couchdb:couchdb /usr/local/{lib,etc}/couchdb /usr/local/var/{lib,log,run}/couchdb
  - service couchdb restart

before_script:
  - curl -X PUT $COUCH_HOST_URL/_config/admins/$COUCH_USER -d '"'$COUCH_PASS'"'

go:
 - 1.13.x

script:
 - go test -v ./...
